services:
  - type: web
    name: crud-ci4-postgres
    runtime: php
    repo: https://github.com/leam-halim/TGS-10.git
    plan: free
    region: singapore
    envVars:
      - key: CI_ENVIRONMENT
        value: production
